/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.co.expenses;

import Clases.CConexion;
import Clases.CLogin;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jarop
 */
public class FormLogin extends javax.swing.JFrame {

    
    CConexion con = new CConexion();
    Connection conectar = con.estableceConexion();
    
    /**
     * Creates new form Inicio
     */
    public FormLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        fondo = new javax.swing.JPanel();
        nombreTitulo = new javax.swing.JLabel();
        jUsuario = new javax.swing.JPanel();
        jNombreUser = new javax.swing.JLabel();
        jInsertarContraseña1 = new javax.swing.JPasswordField();
        jContraseña1 = new javax.swing.JLabel();
        jInsertarNombre = new javax.swing.JTextField();
        bAccess = new java.awt.Button();
        jCrearUsuario = new javax.swing.JPanel();
        jNombreUsuarioNuevo = new javax.swing.JLabel();
        jContraseña2 = new javax.swing.JPasswordField();
        jNuevoUsuario = new javax.swing.JTextField();
        jContraseña = new javax.swing.JLabel();
        bCreateAccount = new java.awt.Button();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.cyan);
        setName("inicio"); // NOI18N

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        nombreTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nombreTitulo.setForeground(new java.awt.Color(204, 0, 51));
        nombreTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreTitulo.setText("CO - EXPENSES");

        jUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Acceso"), "Acceso"));
        jUsuario.setName("Login"); // NOI18N

        jNombreUser.setText("User:");

        jContraseña1.setText("Password:");

        jInsertarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertarNombreActionPerformed(evt);
            }
        });

        bAccess.setLabel("Access");
        bAccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAccessMouseClicked(evt);
            }
        });
        bAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAccessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jUsuarioLayout = new javax.swing.GroupLayout(jUsuario);
        jUsuario.setLayout(jUsuarioLayout);
        jUsuarioLayout.setHorizontalGroup(
            jUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUsuarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bAccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jContraseña1)
                    .addComponent(jNombreUser)
                    .addComponent(jInsertarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jInsertarContraseña1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jUsuarioLayout.setVerticalGroup(
            jUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUsuarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jNombreUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInsertarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jContraseña1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInsertarContraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jCrearUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Nuevo Usuario"));
        jCrearUsuario.setName("CreateAccount"); // NOI18N

        jNombreUsuarioNuevo.setText("User:");

        jContraseña.setText("Password:");

        bCreateAccount.setLabel("New User");
        bCreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCreateAccountMouseClicked(evt);
            }
        });
        bCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCrearUsuarioLayout = new javax.swing.GroupLayout(jCrearUsuario);
        jCrearUsuario.setLayout(jCrearUsuarioLayout);
        jCrearUsuarioLayout.setHorizontalGroup(
            jCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCrearUsuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jContraseña)
                    .addComponent(jNombreUsuarioNuevo)
                    .addGroup(jCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jNuevoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(jContraseña2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jCrearUsuarioLayout.setVerticalGroup(
            jCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCrearUsuarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jNombreUsuarioNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jContraseña2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(bCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(nombreTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoLayout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(98, 98, 98)
                    .addComponent(jCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(nombreTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fondoLayout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(90, 90, 90)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAccessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAccessMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bAccessMouseClicked

    private void jInsertarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInsertarNombreActionPerformed

    private void bCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateAccountActionPerformed
        Clases.CNewUsuer objetoNewUser = new Clases.CNewUsuer();
        objetoNewUser.crearUsuario(jNuevoUsuario, jContraseña2);
    }//GEN-LAST:event_bCreateAccountActionPerformed

    private void bAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAccessActionPerformed
        Clases.CLogin objetoLogin = new Clases.CLogin();
        objetoLogin.validarUsuario(jInsertarNombre, jInsertarContraseña1);
    }//GEN-LAST:event_bAccessActionPerformed

    private void bCreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCreateAccountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bCreateAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bAccess;
    private java.awt.Button bCreateAccount;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jContraseña;
    private javax.swing.JLabel jContraseña1;
    private javax.swing.JPasswordField jContraseña2;
    private javax.swing.JPanel jCrearUsuario;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPasswordField jInsertarContraseña1;
    private javax.swing.JTextField jInsertarNombre;
    private javax.swing.JLabel jNombreUser;
    private javax.swing.JLabel jNombreUsuarioNuevo;
    private javax.swing.JTextField jNuevoUsuario;
    private javax.swing.JPanel jUsuario;
    private javax.swing.JLabel nombreTitulo;
    // End of variables declaration//GEN-END:variables
}
